#include <stdlib.h>
#include <stdio.h>

#include "dice.h"

void trinket(void) {
	switch (d(100)) {
		case   1: printf("A mummified goblin hand\n"); break;
		case   2: printf("A piece of crystal that faintly glows in the moonlight\n"); break;
		case   3: printf("A gold coin minted in an unknown land\n"); break;
		case   4: printf("A diary written in a language you don't know\n"); break;
		case   5: printf("A brass ring that never tarnishes\n"); break;
		case   6: printf("An old chess piece made from glass\n"); break;
		case   7: printf("A pair of knucklebone dice, each with a skull symbol on the side that would normal show six pips\n"); break;
		case   8: printf("A smal idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it\n"); break;
		case   9: printf("A rope necklace from which dangles four mummified elf fingers\n"); break;
		case  10: printf("The deed for a parcel of land in a realm unknown to you\n"); break;
		case  11: printf("A 1-ounce block made from an unknown metal\n"); break;
		case  12: printf("A small coth doll skewered with needles\n"); break;
		case  13: printf("A tooth from an unknown beast\n"); break;
		case  14: printf("An enormous scale,perhaps from a dragon\n"); break;
		case  15: printf("A bright green feather\n"); break;
		case  16: printf("An old divination card bearing your likeness\n"); break;
		case  17: printf("A glass orb filled with moving smoke\n"); break;
		case  18: printf("A 1-pound egg with a bright red shell\n"); break;
		case  19: printf("A pipe that blows bubbles\n"); break;
		case  20: printf("A glass jar containing a weird bit of flesh floating in pickling fluid\n"); break;
		case  21: printf("A tiny gnome-crafted music box that plays a song you dimly remember from your childhood\n"); break;
		case  22: printf("A small wooden statuette of a smug halfling\n"); break;
		case  23: printf("A brass orb etched with strange runes\n"); break;
		case  24: printf("A multicolored stone disk\n"); break;
		case  25: printf("A tiny silver icon of a raven\n"); break;
		case  26: printf("A bag containing forty-seven humanoid teeth, one of which is rotten\n"); break;
		case  27: printf("A shard of obsidian that always feels warm to the touch\n"); break;
		case  28: printf("A dragon's bony talon hanging from a plain leather necklace\n"); break;
		case  29: printf("A pair of old socks\n"); break;
		case  30: printf("A blank book whose pages refuese to hold ink, chalk, graphite, or any other substance or marking\n"); break;
		case  31: printf("A silver badge in the shape of a five-pointed star\n"); break;
		case  32: printf("A knife that belonged to a relative\n"); break;
		case  33: printf("A glass vial filled with nail clippings\n"); break;
		case  34: printf("A rectangular metal device with two tiny metal cups on one end that throws sparks when wet\n"); break;
		case  35: printf("A white, sequined glove sized for a human\n"); break;
		case  36: printf("A vest with one hundred tiny pockets\n"); break;
		case  37: printf("A small weightless stone block\n"); break;
		case  38: printf("A tiny sketch portrait of a goblin\n"); break;
		case  39: printf("An empty glass vial that smells of perfume when opened\n"); break;
		case  40: printf("A gemstone that looks like a lump of coal when examined by anyone but you\n"); break;
		case  41: printf("A scrap of cloth from an old banner\n"); break;
		case  42: printf("A rank of insignia from a lost legionnaire\n"); break;
		case  43: printf("A tiny silver bell without a clapper\n"); break;
		case  44: printf("A mechanical canary inside a gnomish lamp\n"); break;
		case  45: printf("A tiny chest carved to look like it has numerous feet on the bottom\n"); break;
		case  46: printf("A dead sprite inside a clear glass bottle\n"); break;
		case  47: printf("A metal can that has no opening but sounds as if it is filled with broken glass\n"); break;
		case  48: printf("A glass orb filled with water in which swims a clockwork goldfish\n"); break;
		case  49: printf("A silver spoon with an 'M' engraved on the handle\n"); break;
		case  50: printf("A whistle made from gold-colored wood\n"); break;
		case  51: printf("A dead scarab beetle the size of your hand\n"); break;
		case  52: printf("Two toy soldiers, one with a missing head\n"); break;
		case  53: printf("A small box filled with different-sized buttons\n"); break;
		case  54: printf("A candle that cannot be lit\n"); break;
		case  55: printf("A tiny cage with no door\n"); break;
		case  56: printf("An old key\n"); break;
		case  57: printf("An indecipherable treasure map\n"); break;
		case  58: printf("A hilt from a broken sword\n"); break;
		case  59: printf("A rabbit's foot\n"); break;
		case  60: printf("A glass eye\n"); break;
		case  61: printf("A cameo carved in the likeness of a hideous person\n"); break;
		case  62: printf("A silver skull the size of a coin\n"); break;
		case  63: printf("An alabaster mask\n"); break;
		case  64: printf("A pyramid of sticky black incense that smells very bad\n"); break;
		case  65: printf("A nightcap that when worn gives you pleasant dreams\n"); break;
		case  66: printf("A single caltrop made from bone\n"); break;
		case  67: printf("A gold monocle frame without the lens\n"); break;
		case  68: printf("A 1-inch cube each side painted a different color\n"); break;
		case  69: printf("A crystal knob from a door\n"); break;
		case  70: printf("A small packet filled with pink dust\n"); break;
		case  71: printf("A fragment of a beautiful song written as musical notes on two pieces of parchment\n"); break;
		case  72: printf("A silver teardrop earring made from a real teardrop\n"); break;
		case  73: printf("The shell of an egg painted with scenes of human misery in disturbing detail\n"); break;
		case  74: printf("A fan that when unfolded show s sleeping cat\n"); break;
		case  75: printf("A set of bone pipes\n"); break;
		case  76: printf("A four-leaf clover pressed inside a book discussing manners and etiquette\n"); break;
		case  77: printf("A sheet of parchment upon which is draw an complex mechanical contraption\n"); break;
		case  78: printf("An ornate scabbard that fits no blade you have found so far\n"); break;
		case  79: printf("An invitation to a party where a murder happened\n"); break;
		case  80: printf("A bronze pentacle with an etching of a rat's head in its center\n"); break;
		case  81: printf("A purple hankerchief embroidered with the name of a powerful archmage\n"); break;
		case  82: printf("Half of a floorplan for a temple, castle, or some other structure\n"); break;
		case  83: printf("A bit of folded cloth that when unfolded turns into a stylish cap\n"); break;
		case  84: printf("A recipt of deposit at a bank in a far-flung city\n"); break;
		case  85: printf("A diary with seven pages missing\n"); break;
		case  86: printf("An empty silver snuffbox bearing an inscription on the surface that says \"dreams\"\n"); break;
		case  87: printf("An iron holy symbol devoted to an unknown god\n"); break;
		case  88: printf("A book that tells the story of a legendary hero's rise and fall with the last chapter missing\n"); break;
		case  89: printf("A vial of dragon blood\n"); break;
		case  90: printf("An ancient arrow of elven design\n"); break;
		case  91: printf("A needle that never bends\n"); break;
		case  92: printf("An ornate brooch of dwarven design\n"); break;
		case  93: printf("An empty wine bottle bearing a pretty label that says, \"The Wizard of Wines Winery, Red Dragon Crush, 331422-W\"\n"); break;
		case  94: printf("A mosaic tile with a multicolored, glazed surface\n"); break;
		case  95: printf("A petrified mouse\n"); break;
		case  96: printf("A black pirate flag adorned with a dragon's skull and crossbones\n"); break;
		case  97: printf("A tiny mechanical crab or spider that moves about when it's not being observed\n"); break;
		case  98: printf("A glass jar containing lard with a label that reads, \"Griffon Grease\"\n"); break;
		case  99: printf("A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body\n"); break;
		case 100: printf("A metal urn containing the ashes of a hero\n"); break;
	}
}